POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Horst23d",
    "number": "09-1234556"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Horst"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "666"
}